### ISSUE TITLE
Usecase Proposal: chess player

### ISSUE THREAD

**Issue by thomas-quadratic** [zama-ai/fhe-tutorials#11]
This is a usecase proposal for an automated chess player.

## Introduction
We propose a privacy-preserving chess automated player as a playground for concrete-ML.
Interestingly, this simple example has many facets to it:

  - Neural Network: model to learn to evaluate game states.
  - Optimisation: minimax algorithm searching several moves ahead to optimise chances of winning.
  - Chess rules: computing potential moves from a game state.

Perhaps surpisingly, it seems that the most difficult computation to perform on tfhe-encrypted data is the chess rules.
Programming complexe rules in tfhe is non-trivial as it requires conditional control flows (if-else).
Chess has well defined rules of a certain complexity that benefits from many implementations, and thus makes for a good playground to explore rule-based programs in tfhe.
Furthermore, chess is a very popular game that people can try, making a potentially attractive demo app.

## Deliverables

The solution would be a demo client/server app which would demonstrate the feasability of the usecase, together with explanations of the methods and choices made along the way.
Concretely, the deliverables could include:

  - Extended gist or series of posts on the project
  - Code and data for both client and server
  - Demo App (optional)

### Minimum Viable Product (MVP)

The first part would consist of putting together an automated player capable of choosing the best move from a set of potential moves.
This way, we avoid having to code the chess rules, and we focus on the neural network.
We can even avoid searching moves ahead as the AI should give us good estimates for the next moves already (depth=1).

Once the model is trained and saved, the client-server architecture can be put in place.
The client in this scenario is responsible for sending game state + admissible next game states, which it can compute on cleartext.
We can finish off this first version with a complete demo app.

From here, we can take several directions.

### Chess Rules

As mentionned in the introduction, it would be interesting to see how much we can compute intricate rules on encrypted data.
The server could be improved with the capacity to deduce all admissible moves from a game state, which protects it from client's omission attack.

### FHE-friendly neural network

Develop a FHE-friendly NN following the following (paper)[https://arxiv.org/abs/2302.01584]
It is being estimated that we could gain a 10x improvement in computation time on tabular data such as for chess.

### Potential Difficulties

The first part has little risk, as it fits quite well with the concrete-ML library.
We thus can get a MVP with little risk before getting to improvements.
However, to go further, it could potentially be much more difficult and arbitrage will probably have to be made.

### Macro Sizing

  - MVP: 6-10 days
  - Chess Rules: 6-10 days
  - TT-TFHE NN: 6-10 days

**Comment by bcm-at-zama** [comment]
Issues are to be generated in https://github.com/zama-ai/bounty-and-grant-program/issues
